export const ADICIONA_PROJETOS = 'ADICIONA_PROJETOS'
export const ALTERA_PROJETOS = 'ALTERA_PROJETOS'
export const EXCLUIR_PROJETOS = 'EXCLUIR_PROJETOS'
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

export const NOTIFICAR = 'NOTIFICAR'


export const DEFINIR_TAREFAS = 'DEFINIR_TAREFAS'